### ISSUE TITLE
First issue :/

### ISSUE THREAD

**Issue by Skalin** [Mrnda/IPK-Math-server#1]
root@muchreal:/home/xskala11/IPK2$ node server.js
Connection from: 31.30.101.15

/home/xskala11/IPK2/server.js:15
       if(data.toString().startsWith("HELLO"))
                          ^
TypeError: Object SSH-2.0-libssh2_1.7.0
 has no method 'startsWith'
    at Socket.<anonymous> (/home/xskala11/IPK2/server.js:15:27)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)

**Comment by Skalin** [comment]
Při pokusu o připojení dojde k pádu serveru

**Comment by mrnustik** [comment]
Issue was with bad NodeJs version.
